# Generated by Django 4.2 on 2025-06-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='type',
            new_name='substance_type',
        ),
    ]
