# Generated by Django 4.2 on 2025-06-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_rename_type_goal_substance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_unit',
            field=models.CharField(default='%', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_value',
            field=models.FloatField(default=100),
        ),
    ]
