# Generated by Django 4.2 on 2025-06-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_current_value_goal_end_date_goal_target_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
