# Generated by Django 4.2 on 2025-06-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cannabis', 'Cannabis'), ('alcohol', 'Alcohol')], max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('thc_content', models.FloatField(blank=True, null=True)),
                ('cbd_content', models.FloatField(blank=True, null=True)),
                ('strain_type', models.CharField(max_length=20, null=True)),
                ('source_url', models.URLField()),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('scrape_status', models.CharField(default='active', max_length=20)),
                ('is_promoted', models.BooleanField(default=False)),
                ('vendor_priority', models.IntegerField(default=0)),
                ('business_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
