# Generated by Django 4.2 on 2025-06-23 02:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mindful_days', models.IntegerField(default=0)),
                ('sleep_quality', models.FloatField(default=0)),
                ('sleep_improvement', models.FloatField(default=0)),
                ('mood_average', models.FloatField(default=0)),
                ('mood_trend', models.CharField(default='stable', max_length=20)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('substance', models.CharField(choices=[('cannabis', 'Cannabis'), ('alcohol', 'Alcohol'), ('both', 'Both'), ('none', 'None'), ('wellness', 'Wellness')], max_length=20)),
                ('amount', models.CharField(max_length=100)),
                ('mood', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sleep_quality', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('effects', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('sleep', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('vice_type', models.CharField(choices=[('cannabis', 'Cannabis'), ('alcohol', 'Alcohol'), ('both', 'Both'), ('none', 'None'), ('wellness', 'Wellness')], max_length=20)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('spending', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(blank=True, max_length=100)),
                ('time_of_day', models.CharField(blank=True, max_length=20)),
                ('mood_before', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_after', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'date'], name='tracking_jo_user_id_b7c907_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['substance'], name='tracking_jo_substan_57fda0_idx'),
        ),
        migrations.AddIndex(
            model_name='consumptionstats',
            index=models.Index(fields=['user', 'date'], name='tracking_co_user_id_7feb0f_idx'),
        ),
        migrations.AddIndex(
            model_name='consumptionstats',
            index=models.Index(fields=['vice_type'], name='tracking_co_vice_ty_33d355_idx'),
        ),
    ]
