# Generated by Django 4.2 on 2025-06-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_distance',
        ),
        migrations.AddField(
            model_name='user',
            name='consumption_goals',
            field=models.JSONField(blank=True, default=list, help_text="e.g., ['sleep', 'pain_relief', 'celebration']"),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_effects',
            field=models.JSONField(blank=True, default=list, help_text="e.g., ['relaxation', 'creativity', 'social']"),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_categories',
            field=models.JSONField(blank=True, default=list, help_text="e.g., ['cannabis', 'wine', 'beer', 'spirits']"),
        ),
        migrations.AddField(
            model_name='user',
            name='tolerance_level',
            field=models.CharField(blank=True, help_text='Overall tolerance level', max_length=20),
        ),
    ]
