# Generated by Django 5.2.3 on 2025-06-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_tier',
            field=models.CharField(blank=True, help_text="e.g., 'free', 'premium'", max_length=20),
        ),
    ]
